apiVersion: v1
kind: Service
metadata:
  name: helloworld
  namespace: udacity
spec:
  type: LoadBalancer
  selector:
    app: helloworld
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
